# Generated by Django 5.2.17 on 2026-09-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tentativa_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='palavra',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='palavra',
            name='traducao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
