# Generated by Django 5.2.17 on 2026-09-13 15:34

from django.db import migrations, models


def verificar_comparacoes(apps, schema_editor):
    Comparacao = apps.get_model('core', 'Comparacao')
    registros = Comparacao.objects.using(schema_editor.connection.alias)
    problemas = []
    for campos in [('modulo_id', 'ordem'), ('modulo_id', 'palavra_base_id', 'palavra_comparada_id')]:
        duplicados = registros.values(*campos).annotate(total=models.Count('pk')).filter(total__gt=1)
        for grupo in duplicados:
            filtro = {campo: grupo[campo] for campo in campos}
            ids = list(registros.filter(**filtro).values_list('pk', flat=True))
            problemas.append(f'Comparacao: {filtro}, IDs {ids}')
    for comparacao in registros.select_related('palavra_base', 'palavra_comparada').iterator():
        if comparacao.palavra_base_id == comparacao.palavra_comparada_id:
            problemas.append(f'Comparacao ID {comparacao.pk}: palavras iguais')
        if (
            comparacao.palavra_base.modulo_id != comparacao.modulo_id
            or comparacao.palavra_comparada.modulo_id != comparacao.modulo_id
        ):
            problemas.append(f'Comparacao ID {comparacao.pk}: palavra de outro módulo')
    if problemas:
        raise RuntimeError(
            'Corrija as comparações antes de migrar. Nenhum registro foi alterado:\n'
            + '\n'.join(problemas)
        )


class Migration(migrations.Migration):
    atomic = True

    dependencies = [
        ('core', '0004_estrutura_didatica_segura'),
    ]

    operations = [
        migrations.RunPython(verificar_comparacoes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='comparacao',
            constraint=models.UniqueConstraint(fields=('modulo', 'ordem'), name='ordem_comparacao_unica_por_modulo'),
        ),
        migrations.AddConstraint(
            model_name='comparacao',
            constraint=models.UniqueConstraint(fields=('modulo', 'palavra_base', 'palavra_comparada'), name='comparacao_unica_por_modulo'),
        ),
        migrations.AddConstraint(
            model_name='comparacao',
            constraint=models.CheckConstraint(condition=models.Q(('palavra_base', models.F('palavra_comparada')), _negated=True), name='comparacao_palavras_diferentes'),
        ),
    ]
