# Generated by Django 5.2.12 on 2026-09-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usuario_email_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresso',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
