# Generated by Django 5.2.17 on 2026-09-25 02:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_progresso_concluido_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desafio', models.PositiveSmallIntegerField()),
                ('versao', models.CharField(max_length=40)),
                ('requisicao', models.UUIDField(unique=True)),
                ('frase', models.CharField(max_length=255)),
                ('transcricao', models.CharField(blank=True, max_length=255)),
                ('nota', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('avaliacao', models.JSONField()),
                ('criada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tentativas_desafio', to='core.modulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_desafio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criada_em', 'pk'],
                'indexes': [models.Index(fields=['usuario', 'modulo', 'versao', 'desafio'], name='desafio_usuario_versao')],
                'constraints': [models.CheckConstraint(condition=models.Q(('nota__lte', 100)), name='desafio_nota_ate_100')],
            },
        ),
    ]
